language: cpp

notifications:
  email: false
  
sudo: required

os:
  - linux
  - osx

branches:
  only:
    - master

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9

before_install:
  - if [[ $TRAVIS_OS_NAME == linux   ]]; then LINUX=true; fi
  - if [[ $TRAVIS_OS_NAME == osx     ]]; then OSX=true; fi
  
  - if [[ $OSX ]]; then brew update; fi

install:
  - git submodule update
  - if [[ $OSX ]]; then brew install icu4c pango; brew link --force gettext; fi
  - if [[ $OSX ]]; then export ICU_ROOT=/usr/local/opt/icu4c ; fi
  - wget --no-check-certificate https://www.cmake.org/files/v3.3/cmake-3.3.1-Linux-x86_64.sh
  - sudo sh cmake-3.3.1-Linux-x86_64.sh --skip-license --prefix=/usr

  - wget -O leptonica.zip https://github.com/egorpugin/leptonica/archive/master.zip
  - unzip leptonica.zip -d .
  - cmake -Hleptonica-master -Bleptonica-master/build -DSTATIC=1
  - make -C leptonica-master/build

  - wget -O tesseract.zip https://github.com/tesseract-ocr/tesseract/archive/master.zip
  - unzip tesseract.zip -d .
  - cmake -Htesseract-master -Btesseract-master/build -DLeptonica_BUILD_DIR=leptonica-master/build -DSTATIC=1
  - make -C tesseract-master/build

  - if [[ $LINUX && "$CXX" = "g++" ]]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

script:
  - mkdir build
  - cd build
  - cmake .. -DADD_INCLUDE_DIR=tesseract-master/ccutil -DLeptonica_BUILD_DIR=leptonica-master/build -DTesseract=tesseract-master/build
  - make