language: cpp

notifications:
  email: false
  
sudo: required

os:
  - linux
  - osx

branches:
  only:
    - master

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9

before_install:
  - pip install --user codecov
  - export BASEDIR=`pwd`
  - if [[ $TRAVIS_OS_NAME == linux   ]]; then LINUX=true; fi
  - if [[ $TRAVIS_OS_NAME == osx     ]]; then OSX=true; fi
  
  - if [[ $OSX ]]; then brew update; fi
after_success:
  - codecov

install:
  - git submodule update
  - if [[ $OSX ]]; then brew install icu4c pango; brew link --force gettext; fi
  - if [[ $OSX ]]; then export ICU_ROOT=/usr/local/opt/icu4c ; fi
  - wget --no-check-certificate https://www.cmake.org/files/v3.3/cmake-3.3.1-Linux-x86_64.sh
  - sudo sh cmake-3.3.1-Linux-x86_64.sh --skip-license --prefix=/usr

  - if [[ $LINUX && "$CXX" = "g++" ]]; then sudo apt-get install -qq g++-4.9; fi
  - if [[ $LINUX && "$CXX" = "g++" ]]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - g++ --version

  - wget -O leptonica.zip https://github.com/egorpugin/leptonica/archive/master.zip
  - unzip leptonica.zip -d .
  - cmake -Hleptonica-master -Bleptonica-master/build -DSTATIC=1
  - make -C leptonica-master/build

  - wget -O tesseract.zip https://github.com/tesseract-ocr/tesseract/archive/master.zip
  - unzip tesseract.zip -d .
  - cmake -Htesseract-master -Btesseract-master/build -DLeptonica_BUILD_DIR=${BASEDIR}/leptonica-master/build -DSTATIC=1
  - make -C tesseract-master/build
  - wget -O crypto-algorithms.zip https://github.com/B-Con/crypto-algorithms/archive/master.zip
  - unzip crypto-algorithms.zip -d .
  - wget -O mongoose.zip https://github.com/cesanta/mongoose/archive/master.zip
  - unzip mongoose.zip -d .
  - wget -O json.zip https://github.com/nlohmann/json/archive/master.zip 
  - unzip json.zip -d .
  - wget -O sqlite.zip https://www.sqlite.org/snapshot/sqlite-amalgamation-201601141433.zip 
  - unzip sqlite.zip -d ./sqlite-master

script:
  - mkdir build
  - cmake -H${BASEDIR} -B${BASEDIR}/build -DADD_INCLUDE_DIR=${BASEDIR}/tesseract-master/ccutil -DLeptonica_BUILD_DIR=${BASEDIR}/leptonica-master/build -DTesseract_BUILD_DIR=${BASEDIR}/tesseract-master/build -DMongoose_DIR=${BASEDIR}/mongoose-master -DCryptoAlgorithms_DIR=${BASEDIR}/crypto-algorithms-master -DJson_DIR=${BASEDIR}/json-master/src -DSQLite_DIR=${BASEDIR}/sqlite-master
  - cd build
  - make
