os: Visual Studio 2015

platform:
  - Win32
  - Win64

configuration:
  - Debug

artifacts:
  - path: restserver.zip
    name: restserver

before_build:
  - if %platform%==Win32 set generator=Visual Studio 14
  - if %platform%==Win64 set generator=Visual Studio 14 Win64
  - if %platform%==Win32 set vcplatform=Win32
  - if %platform%==Win64 set vcplatform=x64
  - set cwd=%cd%
  - ps: Start-FileDownload 'https://github.com/egorpugin/leptonica/archive/master.zip' -FileName leptonica.zip
  - 7z x leptonica.zip
  - cmake -Hleptonica-master -Bleptonica-master/build -G "%generator%" -DSTATIC=1
  - msbuild leptonica-master/build/leptonica.sln /p:Platform=%vcplatform% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - ps: Start-FileDownload 'https://github.com/tesseract-ocr/tesseract/archive/master.zip' -FileName tesseract.zip
  - 7z x tesseract.zip
  - cmake -Htesseract-master -Btesseract-master/build -G "%generator%" -DLeptonica_BUILD_DIR=%cwd%\leptonica-master\build -DSTATIC=1
  - msbuild tesseract-master/build/tesseract.sln /p:Platform=%vcplatform% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - git submodule update

after_build:
  - 7z a restserver.zip %cwd%\build\bin\Debug\*.exe %cwd%\build\bin\Debug\*.dll

build_script:
  - mkdir build
  - cmake %cwd% -B%cwd%\build -G "%generator%" -DADD_INCLUDE_DIR=%cwd%\tesseract-master\ccutil -DLeptonica_BUILD_DIR=%cwd%\leptonica-master\build -DTesseract_BUILD_DIR=%cwd%\tesseract-master\build -DSTATIC=1
  - msbuild %cwd%\build\recognizer.sln /p:Platform=%vcplatform% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

deploy:
  release: restserver-v$(appveyor_build_version)
  description: 'Rest сервис распознавания для tesseract-ocr'
  provider: GitHub
  auth_token:
    secure: zVAu1Dg7B/l9ru/eCoQnP6fMbjEJ1evpXNwMI07s31DaOAZ9pjwNu2d+t1e6kfJw
  artifact: restserver.zip
  draft: false
  prerelease: true
  on:
    branch: master                 
    appveyor_repo_tag: true        
